version: '2'
services:

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: curl --retry 3 --connect-timeout 2 --max-time 2  -s 169.254.169.254/latest/meta-data/public-ipv4
      KAFKA_ADVERTISED_HOST_NAME: _{HOSTNAME_COMMAND}
      #KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      KAFKA_CREATE_TOPICS: "tri:5:3"
      KAFKA_ZOOKEEPER_CONNECT: 13.59.176.181:2181
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      HOSTNAME_COMMAND: curl --retry 3 --connect-timeout 2 --max-time 2  -s 169.254.169.254/latest/meta-data/public-ipv4
      KAFKA_ZOOKEEPER_CONNECT: 13.59.176.181:2181
      KAFKA_LOG_DIRS: /kafka2
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9093

  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      HOSTNAME_COMMAND: curl --retry 3 --connect-timeout 2 --max-time 2  -s 169.254.169.254/latest/meta-data/public-ipv4
      KAFKA_ZOOKEEPER_CONNECT: 13.59.176.181:2181
      KAFKA_LOG_DIRS: /kafka3
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9094